CREATE TABLE IF NOT EXISTS
    sensors.vantagepro2plus (
        time TIMESTAMPTZ NOT NULL,
        device_id TEXT NOT NULL,
        temperature DOUBLE PRECISION,
        humidity DOUBLE PRECISION,
        dew_point DOUBLE PRECISION,
        wet_bulb DOUBLE PRECISION,
        heat_index DOUBLE PRECISION,
        wind_chill DOUBLE PRECISION,
        thw_index DOUBLE PRECISION,
        thsw_index DOUBLE PRECISION,
        wind_speed_last DOUBLE PRECISION,
        wind_dir_last DOUBLE PRECISION,
        wind_speed_avg_last_1_min DOUBLE PRECISION,
        wind_dir_avg_last_1_min DOUBLE PRECISION,
        wind_speed_avg_last_2_min DOUBLE PRECISION,
        wind_dir_avg_last_2_min DOUBLE PRECISION,
        wind_speed_high_last_2_min DOUBLE PRECISION,
        wind_dir_at_high_last_2_min DOUBLE PRECISION,
        wind_speed_avg_last_10_min DOUBLE PRECISION,
        wind_dir_avg_last_10_min DOUBLE PRECISION,
        wind_speed_high_last_10_min DOUBLE PRECISION,
        wind_dir_at_high_last_10_min DOUBLE PRECISION,
        rain_size DOUBLE PRECISION,
        rain_rate_last DOUBLE PRECISION,
        rain_rate_high DOUBLE PRECISION,
        rain_last_15_min DOUBLE PRECISION,
        rain_rate_high_last_15_min DOUBLE PRECISION,
        rain_last_60_min DOUBLE PRECISION,
        rain_last_24_hour DOUBLE PRECISION,
        rain_storm DOUBLE PRECISION,
        rain_storm_start_at TIMESTAMPTZ,
        solar_radiation DOUBLE PRECISION,
        uv_index DOUBLE PRECISION,
        rx_state TEXT,
        tx_battery_flag TEXT,
        rainfall_day DOUBLE PRECISION,
        rainfall_month DOUBLE PRECISION,
        rainfall_year DOUBLE PRECISION,
        rain_storm_last DOUBLE PRECISION,
        rain_storm_last_start_at TIMESTAMPTZ,
        rain_storm_last_end_at TIMESTAMPTZ,
        barometer_sea_level DOUBLE PRECISION,
        barometer_trend DOUBLE PRECISION,
        barometer_absolute DOUBLE PRECISION,
        temperature_indoor DOUBLE PRECISION,
        humidity_indoor DOUBLE PRECISION,
        dew_point_indoor DOUBLE PRECISION,
        heat_index_indoor DOUBLE PRECISION
    );

SELECT
    create_hypertable (
        'sensors.vantagepro2plus',
        'time',
        if_not_exists => TRUE
    );